Scaffold frontpage
interglobalvision/ondamundial-net pull request #4
Opened 2017-06-21 00:18 UTC by mikeyrayvon

2017-06-21 12:59 UTC, varffs requested changes
When we manipulate time in php I 100% think we should be using the moment.php library https://github.com/fightbulc/moment.php (and the js one when we do in js). It is prebuilt into the boiler and allows much more readable code than any other way of working with time.

2017-06-21 12:59 UTC, varffs commented on front-page.php
> +    <?php echo apply_filters('the_content', $page_sobre->post_content); ?>
Would it be nicer to setup post data here so you can just use `the_content()` and maybe in the future use other template tags? I'm not sure what is best practice

2017-06-21 12:59 UTC, varffs commented on front-page.php
> +  if ($page_sobre != null) {
the empty return value of `get_page_by_path` is null which is false as a condition. so the check can just be on the variable (99% sure of this)

2017-06-21 12:59 UTC, varffs commented on lib/functions-custom.php
> +        'value'   => current_time('timestamp') - (60 * 60 * 24), // UTC -5, 6 hours ago
moment.php is built in to our boiler and will generate these time values with a much more readable codebase. There is a function `subtractHours()` on moment objects that will do this manipulation readably

However why does the function subtract 6 hours? So there is stuff that previously happened, or is this related to servertime?

2017-06-21 12:59 UTC, varffs commented on lib/functions-custom.php
> +      $year = date('Y', $timestamp);
This is obv more readable that previous context, but again moment.php will be much nicer to write and read when getting these values.

2017-06-21 12:59 UTC, varffs commented on lib/functions-custom.php
> +function get_events_array( $query_args = '' ) {
A comment to outline what this function does would be very helpful

2017-06-21 18:00 UTC, mikeyrayvon commented on lib/functions-custom.php
> +        'value'   => current_time('timestamp') - (60 * 60 * 24), // UTC -5, 6 hours ago
ah it actually subtracts 24 hours. forgot to update the comment. yea its to show what already happened

2017-06-21 19:34 UTC, mikeyrayvon commented
moment is only useful when formatting datetime to text. in this case im still manipulating/passing unix timestamps so moment doesnt come into play. were going to organize the schedule dom/content on the front end in js so will use moment there.

2017-06-21 22:04 UTC, merged

2017-06-21 23:00 UTC, varffs commented
moment.php outputs timestamps with `->format('U')` and we've used moment.php to manipulate dates for queries on all the last projects that have used timestamps datepickers. I've written most of that codebase I guess and I promise moment.php makes doing so easier

2017-06-22 02:40 UTC, mikeyrayvon commented
in this case it was easier to do it by hand.

most of the manipulation is going on in js, and were using moment.js there.